---
title: "Informe Cartera"
author: "Informe Mensual"
date: "`r params$Mes` - `r params$Anio`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
params:
  Anio:
    choices:
      - 2019
      - 2020
    value: 2020 
  Mes:
    choices:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    value: 6
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}

htmltools::img(src = knitr::image_uri("www/images/logotipo_finso_analitica_Blanco.svg"),
               style = 'position:absolute; top:70px; right:60px;',
               height = ".65", width = "15%")

```

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```


```{css}

h1{
  
  color: rgb(149, 165, 166);
}


div.fluid-row{
    background-color: rgb(44, 62, 80);
    margin-top:     15px;
    margin-bottom: 15px;
    padding-left:  15px;
    padding-right: 15px;
    padding-top:    5px;
    padding-bottom: 5px;
    border-radius: 5px;
}

div.main-container {
    max-width: 1400px;
}


h1.title.toc-ignore{
    color: rgb(255, 255, 255);
}

h4.author{
    color:rgb(149, 165, 166);
}

h4.date{
    color:rgb(149, 165, 166);
}


h3.subtitulos{
    color: rgb(149, 165, 166);
}

hr {
    border-color: rgb(149, 165, 166);
    margin-bottom: 20px;
    margin-top: 10px;

}

div.contenido{
    margin-top:     1px;
    padding-left:  10px;
    padding-right: 10px;
    padding-top:    1px;
    padding-bottom: 5px;
    background-color: rgb(249, 249, 249);
    border-radius: 5px;
    
}

.nav-pills>li.active>a, .nav-pills>li.active>a:focus, .nav-pills>li.active>a:hover {
    color: #fff;
    background-color: #2C3E50;
}


td:hover {
  background-color: rgb(66, 238, 244);
  
}

```


```{r librerias, include=FALSE}

library(tidyverse)
library(lubridate)
library(knitr)
library(tidyquant)
library(gt)
library(bit64)
library(googlesheets4)
library(pool)
library(janitor)
library(gridExtra)
library(xml2)


```
